# Generated by Django 3.2.11 on 2022-01-29 09:28
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
            ],
            options={
                'db_table': 'movie_data',
            },
        ),
    ]
