# Generated by Django 3.2.11 on 2022-01-30 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa44fb64-81ff-11ec-979b-a86bad13344b'), primary_key=True, serialize=False),
        ),
    ]
