# Generated by Django 3.2.11 on 2022-01-30 19:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.TextField(default=uuid.UUID('c5f88ad2-8200-11ec-979b-a86bad13344b'), max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
